language: python

dist: xenial

sudo: true

cache: pip

python:
    - "3.7"

branches:
  only:
    - master

install:
  - pip3 install -r requirements.txt

script:
  - python3 updater.py

deploy:
  provider: pypi
  user: scriptworld
  password: $PYPI_PASSWORD
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - echo "done !"
